// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Task struct {
	ID           uuid.UUID
	CreatedBy    uuid.UUID
	CreatedAt    time.Time
	LastEditedBy uuid.UUID
	LastEditedAt time.Time
	Title        string
	Link         string
	Platform     uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
	Salt           string
	FirstName      string
	LastName       string
	AuthToken      string
	IsAdminUser    bool
}
