// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: tasks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id,
    created_by,
    created_at,
    last_edited_by,
    last_edited_at,
    title,
    link,
    tags,
    platform

) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
) RETURNING id, created_by, created_at, last_edited_by, last_edited_at, title, link, tags, platform
`

type CreateTaskParams struct {
	ID           uuid.UUID
	CreatedBy    string
	CreatedAt    time.Time
	LastEditedBy string
	LastEditedAt time.Time
	Title        string
	Link         string
	Tags         []string
	Platform     string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastEditedBy,
		arg.LastEditedAt,
		arg.Title,
		arg.Link,
		pq.Array(arg.Tags),
		arg.Platform,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastEditedBy,
		&i.LastEditedAt,
		&i.Title,
		&i.Link,
		pq.Array(&i.Tags),
		&i.Platform,
	)
	return i, err
}
