// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: users.sql

package database

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, email, hashed_password, salt, first_name, last_name, auth_token, is_admin_user FROM users
WHERE email = $1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.Salt,
		&i.FirstName,
		&i.LastName,
		&i.AuthToken,
		&i.IsAdminUser,
	)
	return i, err
}
