// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    email,
    hashed_password,
    salt,
    first_name,
    last_name,
    auth_token,
    is_admin_user,
    verified_user
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
) RETURNING id, email, hashed_password, salt, first_name, last_name, auth_token, is_admin_user, verified_user
`

type CreateUserParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
	Salt           string
	FirstName      string
	LastName       string
	AuthToken      string
	IsAdminUser    bool
	VerifiedUser   bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.HashedPassword,
		arg.Salt,
		arg.FirstName,
		arg.LastName,
		arg.AuthToken,
		arg.IsAdminUser,
		arg.VerifiedUser,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.Salt,
		&i.FirstName,
		&i.LastName,
		&i.AuthToken,
		&i.IsAdminUser,
		&i.VerifiedUser,
	)
	return i, err
}

const editAdminAccess = `-- name: EditAdminAccess :one
UPDATE users
SET is_admin_user = $1
WHERE email = $2
RETURNING id, email, hashed_password, salt, first_name, last_name, auth_token, is_admin_user, verified_user
`

type EditAdminAccessParams struct {
	IsAdminUser bool
	Email       string
}

func (q *Queries) EditAdminAccess(ctx context.Context, arg EditAdminAccessParams) (User, error) {
	row := q.db.QueryRowContext(ctx, editAdminAccess, arg.IsAdminUser, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.Salt,
		&i.FirstName,
		&i.LastName,
		&i.AuthToken,
		&i.IsAdminUser,
		&i.VerifiedUser,
	)
	return i, err
}

const getAllAdminUsers = `-- name: GetAllAdminUsers :many
SELECT 
    email, first_name, last_name 
FROM users
WHERE
    is_admin_user = 1
`

type GetAllAdminUsersRow struct {
	Email     string
	FirstName string
	LastName  string
}

func (q *Queries) GetAllAdminUsers(ctx context.Context) ([]GetAllAdminUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAdminUsersRow
	for rows.Next() {
		var i GetAllAdminUsersRow
		if err := rows.Scan(&i.Email, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT 
    email, first_name, last_name 
FROM users
`

type GetAllUsersRow struct {
	Email     string
	FirstName string
	LastName  string
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(&i.Email, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFromAuthToken = `-- name: GetUserFromAuthToken :one
SELECT id, email, hashed_password, salt, first_name, last_name, auth_token, is_admin_user, verified_user FROM users
WHERE users.auth_token = $1
`

func (q *Queries) GetUserFromAuthToken(ctx context.Context, authToken string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromAuthToken, authToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.Salt,
		&i.FirstName,
		&i.LastName,
		&i.AuthToken,
		&i.IsAdminUser,
		&i.VerifiedUser,
	)
	return i, err
}

const getUserFromEmail = `-- name: GetUserFromEmail :one
SELECT id, email, hashed_password, salt, first_name, last_name, auth_token, is_admin_user, verified_user FROM users
WHERE email = $1
`

func (q *Queries) GetUserFromEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.Salt,
		&i.FirstName,
		&i.LastName,
		&i.AuthToken,
		&i.IsAdminUser,
		&i.VerifiedUser,
	)
	return i, err
}

const setUserVerificationTrue = `-- name: SetUserVerificationTrue :one
UPDATE users
SET verified_use = TRUE
WHERE id = $1
RETURNING id, email, hashed_password, salt, first_name, last_name, auth_token, is_admin_user, verified_user
`

func (q *Queries) SetUserVerificationTrue(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserVerificationTrue, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.Salt,
		&i.FirstName,
		&i.LastName,
		&i.AuthToken,
		&i.IsAdminUser,
		&i.VerifiedUser,
	)
	return i, err
}
